name: deployment

on:
  push:
    branches: 
      - "main"

jobs:
  build_and_deploy:
    runs-on: macos-11

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      - name: checkout code
        uses: actions/checkout@v1
      - name: install dependencies
        run: npm ci
      - name: build
        run: npm run build
