name: deployment

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build
    runs-on: macos-11

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: distribution
          path: ./dist

  dev_delpoy:
    name: Dev Deploy
    runs-on: macos-11

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Download the latest build
        uses: actions/download-artifact@v3
        with:
          name: distribution

      - name: Deploy to Netlify Dev
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: "distribution"
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
