name: deployment

on:
  push:
    branches: 
      - "main"

jobs:
  build:
    runs-on: macos-11

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
